apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscribe
  labels:
    app: subscribe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscribe
  template:
    metadata:
      labels:
        app: subscribe
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: subscribe
          image: "a0018.azurecr.io/subscribe:latest"
          ports:
            - containerPort: 8080
          env:
            - name: _DATASOURCE_ADDRESS
              value: mysql-service
            - name: _DATASOURCE_TABLESPACE
              value: subscribe_db
            - name: _DATASOURCE_USERNAME
              value: root
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass # MySQL 비밀번호가 저장된 Secret 이름
                  key: password    # Secret 내의 키
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
