server:
  port: 8080

spring:
  application:
    name: author
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: author
#<<< EDA / Topic Name
          destination: aivlelibraryminiproj
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: aivlelibraryminiproj
#>>> EDA / Topic Name
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug


server:
  port: 8082

---

spring:
  profiles: docker
  datasource: # 이 블록이 새로 추가됩니다.
    # url: jdbc:mysql://mysql-service:3306/mysql?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mysql://${_DATASOURCE_ADDRESS}:3306/${_DATASOURCE_TABLESPACE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${_DATASOURCE_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD} # 환경 변수 참조
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
     ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: author
          destination: aivlelibraryminiproj
          contentType: application/json
        event-out:
          destination: aivlelibraryminiproj
          contentType: application/json