apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
  labels:
    app: library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: library
          image: "a0018.azurecr.io/library:latest"
          ports:
            - containerPort: 8080
          env:
            - name: _DATASOURCE_ADDRESS
              value: mysql-service
            - name: _DATASOURCE_TABLESPACE
              value: library_db
            - name: _DATASOURCE_USERNAME
              value: root
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
