apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceai
  labels:
    app: serviceai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceai
  template:
    metadata:
      labels:
        app: serviceai
    spec:
      containers:
        - name: serviceai
          image: a0018.azurecr.io/serviceai:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: OPENAI_API_KEY
          volumeMounts:
            - name: azure-volume
              mountPath: /files
      volumes:
        - name: azure-volume
          persistentVolumeClaim:
            claimName: azurefile
