apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-application-ingress
  annotations:
    # HTTP 요청을 HTTPS로 강제 리다이렉션할지 여부를 설정합니다. 테스트 단계에서는 'false'로 두는 것이 편리합니다.
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # 이 IngressClass를 클러스터의 기본 Ingress Class로 설정합니다.
    # 여러 Ingress Controller가 있는 경우 충돌을 피하기 위해 신중하게 사용해야 합니다.
    # 일반적으로는 생략하거나 특정 Ingress를 위한 클래스를 명시하는 것이 좋습니다.
    ingressclass.kubernetes.io/is-default-class: "true" 
spec:
  ingressClassName: nginx
  rules:
    - host: ""
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend # 이 Service는 'frontend' Deployment에 연결된 ClusterIP Service여야 합니다.
                port:
                  number: 8080 # frontend Pod의 컨테이너 포트와 Service 포트가 일치해야 합니다.
          
          # Gateway 애플리케이션에 대한 라우팅 규칙입니다.
          # '/api'로 시작하는 모든 요청을 gateway 서비스로 보냅니다.
          # Gateway는 이 요청을 받아 내부 마이크로서비스로 다시 라우팅합니다.
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
          # AI 서비스가 직접 사진을 서빙하는 경우, 여기에 /files 규칙 추가
          - path: /files # 또는 /generated-images
            pathType: Prefix
            backend:
              service:
                name: serviceai # AI 서비스의 이름
                port:
                  number: 8080