FROM node:22-alpine as build

WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
ENV NODE_OPTIONS=--openssl-legacy-provider
RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginx:stable-alpine

# Nginx 설정 파일을 컨테이너로 복사
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# 빌드된 React 정적 파일을 Nginx 웹 루트로 복사
COPY --from=build /app/dist /usr/share/nginx/html

# Nginx가 8080번 포트에서 리스닝하도록 변경했으므로 EXPOSE도 8080으로 맞춥니다.
EXPOSE 8080

# 컨테이너 시작 시 Nginx 실행
CMD ["nginx", "-g", "daemon off;"]